### ISSUE TITLE
AppModelv2-WebAPI-nodejs sample not working

### ISSUE THREAD

**Issue by olivierHen** [AzureADQuickStarts/AppModelv2-WebAPI-nodejs#3]
Hi folks,

I'm trying to get a token in order to use groove REST Api, but when I'm trying to use Bearer Strategy, I always have the same error : 
{"name":"AzureAD: Bearer Strategy","hostname":"CD002014","pid":23820,"level":30,"msg":"authentication failed due to: token is not found","time":"2016-11-30T13:16:08.845Z","v":0}

I have configure all the options and they work quite well with the OIDC Startegy (which doesn't work with groove API ...) 

Does anyone faces the same issue ?

Olivier

**Comment by lovemaths** [comment]
@olivierHen Bearer Strategy is not for getting a token. OIDC Strategy is the one you should use, what is the problem with groove API?

**Comment by navyasric** [comment]
Closing as the issue was addressed in above comment and has not had a response since. Please reopen if necessary.
