### ISSUE TITLE
How can I get a test token?

### ISSUE THREAD

**Issue by DrakaSAN** [AzureADQuickStarts/AppModelv2-WebAPI-nodejs#5]
I have followed the [MSDN guide](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-devquickstarts-webapi-nodejs) to try to understand how to use the Bearer strategy.

While I understand the general flow of OAuth and how to use passport and the Bearer strategy, I am left with one glaring question at the end of the guide:

- How do I get a token exactly?

I know it will be some sort of HTTP(S) call to microsoft, more probably my tenant, but how do I find out which? Do I have to build another test app that implement the AAD client library just to test if my setup work? Can't I just build the HTTP call in POSTMan or curl? Why?

**Comment by lovemaths** [comment]
@D219 The easiest way to test it is using an id_token.

To get an id_token, fill in your client_id and your redirect_uri in the following url, then go to that url in browser. You will be asked to log in. After that your browser will be redirected to your redirect_uri with an id_token in the fragment.

``` 
https://login.microsoftonline.com/common/oauth2/v2.0/authorize?
client_id=<your_app_client_id>
&response_type=id_token
&redirect_uri=<your_app_redirect_uri>
&response_mode=fragment
&scope=openid
&nonce=123
```

The following is the full documentation on how OpenID connect flow works in AAD: https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-protocols-openid-connect-code

**Comment by navyasric** [comment]
Closing as issue has been answered in above comment. Please reopen if necessary.
