### ISSUE TITLE
Strategy.prototype.jwtVerify: cannot verify token

### ISSUE THREAD

**Issue by jadams2305** [AzureADQuickStarts/AppModelv2-WebAPI-nodejs#7]
Hi,

I trying to connect to the webapi using a token issued using MSAL.JS example in https://github.com/Azure-Samples/active-directory-javascript-graphapi-v2. The token is well formed and I get a good response sending it in the HTTP Bearer header to https://graph.microsoft.com/v1.0/me.
However I keep getting the error "Strategy.prototype.jwtVerify: cannot verify token" when I try to use your example. See log below.

Any idea what is going wrong?

thanks,

Jose

`
{"name":"Windows Azure Active Directory Sample","hostname":"LAPTOP-IJ5NK497","pid":22652,"level":30,"msg":"MongoDB Schema loaded","time":"2019-01-02T20:31:51.264Z","v":0}
{"name":"AzureAD: Bearer Strategy","hostname":"LAPTOP-IJ5NK497","pid":22652,"level":30,"msg":"In BearerStrategy constructor: strategy created","time":"2019-01-02T20:31:51.392Z","v":0}
{"name":"AzureAD: Metadata Parser","hostname":"LAPTOP-IJ5NK497","pid":22652,"level":30,"msg":"Parsing JSON retreived from the endpoint","time":"2019-01-02T20:32:03.890Z","v":0}
{"name":"AzureAD: Metadata Parser","hostname":"LAPTOP-IJ5NK497","pid":22652,"level":30,"msg":"Request to update the Open ID Connect Metadata","time":"2019-01-02T20:32:03.891Z","v":0}
{"name":"AzureAD: Bearer Strategy","hostname":"LAPTOP-IJ5NK497","pid":22652,"level":30,"msg":"In Strategy.prototype.authenticate: received metadata","time":"2019-01-02T20:32:04.006Z","v":0}
{"name":"AzureAD: Bearer Strategy","hostname":"LAPTOP-IJ5NK497","pid":22652,"level":30,"msg":"In Strategy.prototype.authenticate: we will validate the options","time":"2019-01-02T20:32:04.007Z","v":0}
{"name":"AzureAD: Bearer Strategy","hostname":"LAPTOP-IJ5NK497","pid":22652,"level":30,"msg":"In Strategy.prototype.authenticate: access_token is received from request header","time":"2019-01-02T20:32:04.008Z","v":0}
{"name":"AzureAD: Bearer Strategy","hostname":"LAPTOP-IJ5NK497","pid":22652,"level":30,"msg":"In Strategy.prototype.jwtVerify: token is decoded","time":"2019-01-02T20:32:04.009Z","v":0}
{"name":"AzureAD: Metadata Parser","hostname":"LAPTOP-IJ5NK497","pid":22652,"level":30,"msg":"working on key","time":"2019-01-02T20:32:04.009Z","v":0}
{"name":"AzureAD: Bearer Strategy","hostname":"LAPTOP-IJ5NK497","pid":22652,"level":30,"msg":"PEMkey generated","time":"2019-01-02T20:32:04.010Z","v":0}
{"name":"AzureAD: Bearer Strategy","hostname":"LAPTOP-IJ5NK497","pid":22652,"level":30,"msg":"authentication failed due to: In Strategy.prototype.jwtVerify: cannot verify token","time":"2019-01-02T20:32:04.013Z","v":0}
`

**Comment by subukris** [comment]
I'm facing exactly the same issue. When I introspected the access_token in jwt.ms it says that it is a Azure AD V1 token and the "aud" claim seems to be hard-coded.
The id_token is a Azure AD V2 token and has the right "aud" claim. Not sure what is going on with access_token. Will appreciate any useful help/pointer. Thanks!

**Comment by jmprieur** [comment]
@navyasric

**Comment by leonbrag** [comment]
I have the same issue using B2C authentication sample: 

{"name":"AzureAD: Bearer Strategy","hostname":"localhost","pid":19416,"level":30,"msg":"authentication failed due to: In Strategy.prototype.jwtVerify: cannot verify token","time":"2019-09-18T00:51:20.656Z","v":0}

**Comment by derisen** [comment]
Closing as we are archiving this repo. Please refer to [Protect an Node.js & Express web API with Azure Active Directory](https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/tree/main/3-Authorization-II/1-call-api) instead.
